### ISSUE TITLE
Option to bulk delete local branches.

### ISSUE THREAD

**Issue by GiovaniDaSilva** [digao-dalpiaz/DigaoDesk#28]
You happen to have a lot of local branches that are no longer on the server. Deleting one by one takes a long time, and deleting the entire folder, I lose environment settings.

Having a way to select multiple branches and confirm the deletion once would bring agility to the process.

**Comment by digao-dalpiaz** [comment]
Analysis description: Create a form to select multiple branches in specific repository and operate commands using all checked branches.

**Comment by digao-dalpiaz** [comment]
In progress...
