### ISSUE TITLE
GUI multi-language support

### ISSUE THREAD

**Issue by wcxu21** [digao-dalpiaz/DigaoDesk#29]
Hi bro
Can you add multilingual support to the GUI?
I can provide Chinese translation support.
Thanks for your work.

**Comment by digao-dalpiaz** [comment]
Hello, let me do some analysis and I will include multilingual support.

Probably I will create a language file, so you can translate by typing messages in translation file.

I will keep you in touch.

**Comment by digao-dalpiaz** [comment]
I'm starting multi-language support right now!

**Comment by wcxu21** [comment]
Thanks for your work, I will be happy to help translate the Chinese language.

**Comment by digao-dalpiaz** [comment]
Hello @wcxu21 

I finished translation supporting!!!

So, I created json files to languages supporting.

Now, there is two files:
- lang_english.json
- lang_chinese.json

The file "lang_chinese.json" is empty. Please, use english file to create chinese strings.

The translations support is available in this branch: 
https://github.com/digao-dalpiaz/DigaoDesk/tree/translation-support

**Comment by wcxu21** [comment]
Hi @digao-dalpiaz 
I cloned a project and added the translated language files to my project. You can download it and upload it to your project.
https://github.com/wcxu21/DigaoDesk/blob/main/DigaoDeskApp/Languages/lang_chinese.json
You can modify it as needed.
thank you for your support.

**Comment by digao-dalpiaz** [comment]
Awesome,

Could you please open a pull request for this json file ?

**Comment by digao-dalpiaz** [comment]
testing...

**Comment by digao-dalpiaz** [comment]
Hello @wcxu21 ,

Can you please provide chinese translation for these new strings:

`"Apps_Filter_All": "All Applications",`
`"Apps_Filter_Running": "Only Running",`
`"Apps_Filter_Stopped": "Only Stopped",`


Thanks

**Comment by digao-dalpiaz** [comment]
> Hello @wcxu21 ,
> 
> Can you please provide chinese translation for these new strings:
> 
> `"Apps_Filter_All": "All Applications",` `"Apps_Filter_Running": "Only Running",` `"Apps_Filter_Stopped": "Only Stopped",`
> 
> Thanks

Can you provide these three strings in Chinese, please...

You may insert the strings directly here in a comment.
Thanks a lot.

**Comment by digao-dalpiaz** [comment]
Hello,

I already merged this branch into master branch.
Just reviewing last features.

And waiting for last missing Chinese strings.

Thanks
