### ISSUE TITLE
É possível implementar opção de reabrir aplicação quando for parada?

### ISSUE THREAD

**Issue by herlondf** [digao-dalpiaz/DigaoDesk#59]
Há uma aplicação de terceiro em meu servidor, que em intervalos em média de 2 dias, finaliza (crash) e me gera uma imensa dor de cabeça. A ideia seria, monitorar a aplicação, se a mesma for finalizada manual ou por causa de algum crash, o monitor restartá-la.

**Comment by digao-dalpiaz** [comment]
Done!
